import test from 'node:test'
import assert from 'node:assert/strict'
import { WorkspaceRepository } from '../workspace/repository.js'
import { normalizeWorkspace, WORKSPACE_KEY } from '../workspace/schema.js'
import { queryPrompts } from '../workspace/query.js'
import { groupText, promptText } from '../workspace/export.js'
import { readFile } from 'node:fs/promises'

class MemoryStorage { constructor(seed={}){this.data={...seed}}getItem(key){return this.data[key]??null}setItem(key,value){this.data[key]=value} }
const output={title:'Future Beat Tee',direction:'A bold music concept.',prompt:'Complete final production prompt.',age:'Big Kids',product:'T-shirt',production:'DTF'}
const state={intensity:'BOLD',artStyle:'Graffiti pop',character:'Original human character',typography:'Chunky block',palette:'Street neon',material:'Faux puff ink',phrase:'FUTURE BEAT'}

test('workspace survives malformed storage without crashing',()=>{const repo=new WorkspaceRepository(new MemoryStorage({[WORKSPACE_KEY]:'{bad'}));assert.deepEqual(repo.data.prompts,[])})
test('save preserves metadata and prevents accidental duplicates',()=>{const repo=new WorkspaceRepository(new MemoryStorage());const first=repo.createPrompt(output,state,'Build with BooBoo'),second=repo.createPrompt(output,state,'Build with BooBoo');assert.equal(first.created,true);assert.equal(second.created,false);assert.equal(repo.data.prompts.length,1);assert.equal(first.record.intensity,'BOLD');assert.equal(first.record.exactPhrase,'FUTURE BEAT')})
test('favorite, rename, notes, and persistence survive reload',()=>{const storage=new MemoryStorage(),repo=new WorkspaceRepository(storage);const item=repo.createPrompt(output,state,'Shake the Box').record;repo.toggleFavorite(item.id);repo.updatePrompt(item.id,{title:'Renamed Beat',notes:'Try black hoodie.'});const reload=new WorkspaceRepository(storage);assert.equal(reload.findPrompt(item.id).favorite,true);assert.equal(reload.findPrompt(item.id).title,'Renamed Beat');assert.equal(reload.findPrompt(item.id).notes,'Try black hoodie.')})
test('duplicate creates independent record and duplicate-safe title',()=>{const repo=new WorkspaceRepository(new MemoryStorage()),item=repo.createPrompt(output,state).record,copy=repo.duplicatePrompt(item.id);assert.notEqual(copy.id,item.id);assert.equal(copy.title,'Future Beat Tee — Copy');assert.equal(copy.sourcePromptId,item.id)})
test('search filters sorting and favorites work',()=>{const repo=new WorkspaceRepository(new MemoryStorage());const a=repo.createPrompt(output,state,'Build with BooBoo').record;repo.createPrompt({...output,title:'Baby Soft',age:'Newborn',product:'Bodysuit',prompt:'Soft baby prompt.'},{...state,intensity:'PLAYFUL',phrase:'SLEEPY JOY'},'Shake the Box');repo.toggleFavorite(a.id);assert.equal(queryPrompts(repo.data.prompts,{search:'FUTURE BEAT'},[]).length,1);assert.equal(queryPrompts(repo.data.prompts,{age:'Newborn'},[]).length,1);assert.equal(queryPrompts(repo.data.prompts,{status:'Favorites'},[]).length,1);assert.equal(queryPrompts(repo.data.prompts,{sort:'A–Z'},[])[0].title,'Baby Soft')})
test('deleting prompt detaches group but preserves group',()=>{const repo=new WorkspaceRepository(new MemoryStorage()),item=repo.createPrompt(output,state).record;repo.data.collections.push({id:'c1',name:'Crew',description:'',promptIds:[item.id],createdAt:'x',modifiedAt:'x',production:'DTF',intensity:'BOLD'});item.collectionIds=['c1'];repo.persist();repo.deletePrompt(item.id);assert.equal(repo.data.collections.length,1);assert.deepEqual(repo.data.collections[0].promptIds,[])})
test('collection removal does not delete prompt and order can move',()=>{const repo=new WorkspaceRepository(new MemoryStorage()),a=repo.createPrompt(output,state).record,b=repo.createPrompt({...output,title:'Second',prompt:'Second prompt'},state).record;repo.data.collections.push({id:'c1',name:'Crew',description:'',promptIds:[a.id,b.id],createdAt:'x',modifiedAt:'x',production:'DTF',intensity:'BOLD'});repo.moveInGroup('collections','c1',b.id,-1);assert.deepEqual(repo.data.collections[0].promptIds,[b.id,a.id]);repo.removeFromGroup('collections','c1',b.id);assert.ok(repo.findPrompt(b.id));assert.deepEqual(repo.data.collections[0].promptIds,[a.id])})
test('grouped output persists collection, Match My Mini, and Outfit records',()=>{for(const mode of ['Collection Builder','Match My Mini','Outfit Builder']){const repo=new WorkspaceRepository(new MemoryStorage()),grouped={...output,items:[output,{...output,title:'Look Two',prompt:'Second final prompt.'}]};repo.saveOutput(grouped,state,mode);const key=mode==='Collection Builder'?'collections':mode==='Match My Mini'?'matchGroups':'outfitSets';assert.equal(repo.data[key].length,1);assert.equal(repo.data.prompts.length,2)}})
test('backup import merges conflicts with fresh IDs',()=>{const repo=new WorkspaceRepository(new MemoryStorage()),item=repo.createPrompt(output,state).record;repo.mergeBackup({prompts:[item],collections:[],matchGroups:[],outfitSets:[],recent:[]});assert.equal(repo.data.prompts.length,2);assert.notEqual(repo.data.prompts[0].id,repo.data.prompts[1].id)})
test('invalid backup is rejected without destroying workspace',()=>{const repo=new WorkspaceRepository(new MemoryStorage());repo.createPrompt(output,state);assert.throws(()=>repo.mergeBackup({unexpected:true}),/Invalid workspace backup/);assert.equal(repo.data.prompts.length,1)})
test('normalizer preserves valid records when neighbors are malformed',()=>{const data=normalizeWorkspace({prompts:[{title:'Good',prompt:'Valid'},null,{bad:true},{id:'same',title:'One',prompt:'A'},{id:'same',title:'Two',prompt:'B'}]});assert.equal(data.prompts.length,2)})
test('plain, structured, and grouped exports contain correct content',()=>{const item=normalizeWorkspace({prompts:[{...output,...state}]}).prompts[0];assert.equal(promptText(item),item.prompt);assert.match(promptText(item,true),/Creative Intensity: BOLD/);assert.match(groupText({name:'Crew',description:'Set',sharedDNA:'Theme',age:'Kids',production:'DTF',intensity:'BOLD',createdAt:'x',modifiedAt:'x',promptIds:[item.id]},[item]),/1\. BOOMBOX KIDS™/)})
test('workspace UI contains required management actions and Save As New',async()=>{const source=await readFile(new URL('../ui/workspace.js',import.meta.url),'utf8');for(const token of ['ALL PROMPTS','FAVORITES','RECENT','CREATIVE SETS','CLEAR FILTERS','OPEN','COPY','REMIX','DUPLICATE','RENAME','DELETE','SAVE AS NEW','EXPORT WORKSPACE BACKUP','IMPORT &amp; MERGE','MOVE UP','MOVE DOWN'])assert.match(source,new RegExp(token))})
test('responsive workspace keeps cards filters and touch actions usable',async()=>{const css=await readFile(new URL('../styles.css',import.meta.url),'utf8');assert.match(css,/@media \(max-width:980px\)/);assert.match(css,/@media \(max-width:620px\)/);assert.match(css,/\.prompt-card-grid/);assert.match(css,/touch-action:manipulation/);assert.match(css,/\.library-filters>div/);assert.match(css,/min-height:44px/)})
