import { imageExecutionLock } from './promptComposer.js'

export function remixPrompt(source, instructions) {
  const requested = instructions.length ? instructions.join(', ') : 'make it more original and production-ready'
  const creativePush = /more creative|more extra|more bold|more fun|push it|make it hit|boombox mode|stronger concept|more original|fashion-forward/i.test(requested)
    ? 'Strengthen the idea through scale, typography interaction, composition, dimensionality, material contrast, color rhythm, silhouette, depth, controlled negative space, and visual metaphor—not by piling on props. Use controlled maximalism with one clear hero and readable hierarchy.'
    : 'Change only what the requested remix requires and keep the result conceptually coherent.'
  return { title: 'Remixed Kids Apparel Direction', direction: `Preserve the core idea while applying: ${requested}.`, prompt: `${imageExecutionLock}\n\nPreserve the central concept, age, exact text, production method, and recognizable creative intent of this user-supplied kids-apparel prompt unless the user explicitly changes one:\n\n“${source.trim()}”\n\nRemix requirements: ${requested}. ${creativePush} Improve the creative hierarchy and originality without replacing the core idea. Keep all exact quoted phrases exactly as supplied. Ensure age-appropriate styling, readable intentional typography, brand-free original fashion, and no copyrighted characters or trademarked identifiers. Require believable anatomy, correct limbs and fingers, natural posture, coherent faces, correctly rooted hair, structurally believable garments, no duplicates, no floating accessories, and no random text.`, production: instructions.includes('Sublimation optimization') ? 'Sublimation' : 'DTF', age: 'As specified in source', product: 'As specified in source' }
}
